# Generated by Django 2.1.4 on 2018-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='dummy', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
